# setup logging for WSUDOR_Indexer
from WSUDOR_Manager import logging

# Import ContentTypes
from WSUDOR_Object import WSUDOR_Object, WSUDOR_GenObject
from WSUDOR_Image import WSUDOR_Image
from WSUDOR_Collection import WSUDOR_Collection
from WSUDOR_Audio import WSUDOR_Audio
from WSUDOR_WSUebook import WSUDOR_WSUebook
from WSUDOR_WSUebook_Page import WSUDOR_WSUebook_Page 
from WSUDOR_HierarchicalFiles import WSUDOR_HierarchicalFiles 
from WSUDOR_ContentModel import WSUDOR_ContentModel 
from WSUDOR_Volume import WSUDOR_Volume
from WSUDOR_Document import WSUDOR_Document
from WSUDOR_Container import WSUDOR_Container
from WSUDOR_LearningObject import WSUDOR_LearningObject
from WSUDOR_Archive import WSUDOR_Archive

# Import Readux Virtual Objects
from WSUDOR_Readux import WSUDOR_Readux_VirtualBook
from WSUDOR_Readux import WSUDOR_Readux_VirtualVolume
from WSUDOR_Readux import WSUDOR_Readux_VirtualPage
from WSUDOR_Readux import WSUDOR_Readux_VirtualCollection
